// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP37I9FR85O_-KHMfhRbkSD5YsMDhSvSY',
    appId: '1:881072359900:web:53b177f6e668cb2a04a719',
    messagingSenderId: '881072359900',
    projectId: 'new-e-commerce-app-6d004',
    authDomain: 'new-e-commerce-app-6d004.firebaseapp.com',
    storageBucket: 'new-e-commerce-app-6d004.appspot.com',
    measurementId: 'G-0S2DNN88ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0Eryxa8Ra9SbsA_c_wOG3iJDMdCyK7M',
    appId: '1:881072359900:android:11fdad445378bf1e04a719',
    messagingSenderId: '881072359900',
    projectId: 'new-e-commerce-app-6d004',
    storageBucket: 'new-e-commerce-app-6d004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxsgCLf-1vj0vUfJCf8eH1JRxdfpp-fs',
    appId: '1:881072359900:ios:fdbf5e6abb6eb5bf04a719',
    messagingSenderId: '881072359900',
    projectId: 'new-e-commerce-app-6d004',
    storageBucket: 'new-e-commerce-app-6d004.appspot.com',
    iosClientId: '881072359900-5v9gpgrnh5ea31ftvum8o3p5t09q77pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxsgCLf-1vj0vUfJCf8eH1JRxdfpp-fs',
    appId: '1:881072359900:ios:fdbf5e6abb6eb5bf04a719',
    messagingSenderId: '881072359900',
    projectId: 'new-e-commerce-app-6d004',
    storageBucket: 'new-e-commerce-app-6d004.appspot.com',
    iosClientId: '881072359900-5v9gpgrnh5ea31ftvum8o3p5t09q77pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newECommerce',
  );
}
