// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdjtn30HGkmS7Ky-C7UdQqIp2HeeJzblU',
    appId: '1:229129639229:web:21522f79dd171c79d0a154',
    messagingSenderId: '229129639229',
    projectId: 'newapp-6ca27',
    authDomain: 'newapp-6ca27.firebaseapp.com',
    storageBucket: 'newapp-6ca27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ItnizCouqz1dNbWhTldVSq9KY_eS2hA',
    appId: '1:229129639229:android:59ea93681db977b1d0a154',
    messagingSenderId: '229129639229',
    projectId: 'newapp-6ca27',
    storageBucket: 'newapp-6ca27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFWuyIbQnmEZ46QJFaMCz9s2_LSERm4RU',
    appId: '1:229129639229:ios:91cc6efd97fa2f9dd0a154',
    messagingSenderId: '229129639229',
    projectId: 'newapp-6ca27',
    storageBucket: 'newapp-6ca27.appspot.com',
    iosClientId: '229129639229-jn6m9ul6f36vjimv8822kqmagf9bfdhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.newECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFWuyIbQnmEZ46QJFaMCz9s2_LSERm4RU',
    appId: '1:229129639229:ios:91cc6efd97fa2f9dd0a154',
    messagingSenderId: '229129639229',
    projectId: 'newapp-6ca27',
    storageBucket: 'newapp-6ca27.appspot.com',
    iosClientId: '229129639229-jn6m9ul6f36vjimv8822kqmagf9bfdhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.newECommerce',
  );
}
